plugins {
    id 'java-library'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

sourceSets {
    main {
        java {
            exclude 'com/nox/futreal/FutRealGame.java'
        }
    }
}

dependencies {
    api "com.badlogicgames.gdx:gdx:${gdxVersion}"
}
