plugins {
    id 'com.android.application'
}

android {
    namespace 'com.nox.monsters3d'
    compileSdk 34

    defaultConfig {
        applicationId 'com.nox.monsters3d'
        minSdk 23
        targetSdk 34
        versionCode 3
        versionName '0.3-true3d'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
